- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/bagisto

- name: Enable Bagisto site
  ansible.builtin.shell:
    cmd: ln -s /etc/nginx/sites-available/bagisto /etc/nginx/sites-enabled/

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
